# Generated by Django 4.1.7 on 2023-03-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactiontime',
            name='executed_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
