# Generated by Django 4.1.7 on 2023-03-11 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reaction', '0002_alter_reactiontime_executed_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReactionTime',
            new_name='ReactionResult',
        ),
        migrations.RenameField(
            model_name='reactionresult',
            old_name='reaction_time',
            new_name='reaction_result',
        ),
    ]
